//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIT5032_A1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Chinese_Restaurant_ModelContainer : DbContext
    {
        public Chinese_Restaurant_ModelContainer()
            : base("name=Chinese_Restaurant_ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Seat> Seats { get; set; }
        public virtual DbSet<Seat_Booking> Seat_Booking { get; set; }
        public virtual DbSet<Food> Foods { get; set; }
    }
}
